### ISSUE TITLE
ROM map is misformatted

### ISSUE THREAD

**Issue by PikalaxALT** [zladx/LADX-Disassembly#120]
The file `src/ROM map.md` is formatted such that all banks appear on the same line when viewed in a web browser, rather than each bank on its own line as was likely intended. Consider adding backslashes to the end of each line to insert line breaks, or structure the map as a table.

**Comment by kemenaran** [comment]
Oh yes, that's right. I just fixed it, it should be clearer now. Thanks for the report!
