### ISSUE TITLE
Fix palette of Link and NPCs tiles

### ISSUE THREAD

**Issue by kemenaran** [zladx/LADX-Disassembly#209]
Link sprite sheet (and NPCs sprite sheets in general) are PNG files, but those are not easy to understand. For a start, the palette seems wrong.

_Example of Link's PNG sprite sheet with an incorrect palette_
![link_1 cgb](https://user-images.githubusercontent.com/179923/79142689-2a95b780-7dbc-11ea-884c-899ee7a077a4.png)

We should edit these PNG sprite sheets to make them easier to edit–beginning with fixing the palette of the PNG files (while still compiling to the same `.2bpp` in the end).

## How

`rgbgfx` seems to have support for alternate grayscale palettes. Probably the PNG files can be re-extracted using a better palette, and then `rgbgfx` invoked with the correct options would be able to compile the file back to the original `.2bpp`.

**Comment by kemenaran** [comment]
Based on a discussion with Aria Hiroshi 64, there should be an easy solution to this:

1. Import the PNG spritesheet into GIMP
2. In GIMP, index the image to 4 colors
3. Change the color map colors (but without changing the color map order)
4. Save the PNG

At compile time, `rgbgfx` will still use the color map in the order colors are declared, so it will still compile to the right 2bpp values.

(It seems this is how pokecrystal does it.)

**Comment by kemenaran** [comment]
(It seems ImageMagik can also be used to convert the PNG to indexed, then to change the colors.)

**Comment by AriaHiro64** [comment]
Check my pull request #260
