### ISSUE TITLE
Gigaleak source files for disassembly?

### ISSUE THREAD

**Issue by Ayymoose** [zladx/LADX-Disassembly#332]
Has anyone actually managed to use the Nintendo Gigaleak actual source files for Links Awakening DX as a reference for this project?

**Comment by mdtauk** [comment]
Including any leaked code, would be illegal, and would cause Nintendo to take action to take down the project.

For it to be legal, it needs to be a **Clean Room** decompilation and reverse engineering effort

**Comment by kemenaran** [comment]
Yep, exactly. This project doesn't (and can't) use knowledge acquired from leaked code.

From the Discord FAQ:

> If you ever want to contribute to the LADX disassembly, do not ever look at leaked source code.
> The LADX disassembly is a clean room reverse-engineered version of the code. It must not be tainted by functions or variables extracted from the > original source code – or even by external knowledge gained by looking at it.
> 
> **FAQ: Does the leaked source code make the disassembly obsolete?**
> 
> Absolutely not. Although the original source code can now be obtained by dubious means, the reverse-engineered code is still valuable.
> 
> The leaked source code is almost 30 years old. Judging by other leaks, it is likely a pile of poorly formatted source files, with lot of japanese, using > an obsolete toolchain of compilers.
> 
> Unlile the leaked code;
> - The disassembled code is likely much better organized and clean;
> - The functions and variables names are probably way easier to understand, and don't need lot of Japanese comments to be explained;
> - The disassembled version uses a modern toolchain that can recompile the code easily.
> 
> In short, the disassembly is a better start for ROM hacks or research projects.
>
> **FAQ: I looked at internal screenshots or content, but not at the source code. Is that an issue?**
> 
> Likely not. Although you should probably be careful when choosing to look at leaked intellectual property, this is not the kind of knowledge tainting > the reverse-engineering work.
> 
> What shouldn't be touched is internal knowledge about the source code structure, or the variable names, or comments explaining some code structures. But > binary content (internal builds, graphics) is probably not considered as tainting the clean room.>
