### ISSUE TITLE
Name the few unamed tilemaps

### ISSUE THREAD

**Issue by kemenaran** [zladx/LADX-Disassembly#345]
In `src/data/backgrounds/` are some tilemaps that have no name (like tilemap_03, tilemap_06, tilemap_09, etc).

They seem to be related to the inventory, but they are not named yet.

We should understand what they do, and name them accordingly.

**Comment by Rangi42** [comment]
Named constants for the `wBGMapToLoad` values would help with that.

**Comment by kemenaran** [comment]
#432 adds named constants for `wBGMapToLoad`.

Now only `TILEMAP_09` remains unidentified.

**Comment by kemenaran** [comment]
Since #435 all tilemaps are now labeled.
