### ISSUE TITLE
Label palettes data

### ISSUE THREAD

**Issue by kemenaran** [zladx/LADX-Disassembly#377]
There's a lot of raw palette data in `src/code/palettes.asm`. They are properly split up, but should be labeled according to their actual usage.

**Comment by kemenaran** [comment]
This has mostly been fixed by the numerous PRs of @KelseyHigham.

Does this issue still needs to remain opened?

**Comment by KelseyHigham** [comment]
I've labeled all the palettes I'm aware of. Though there might be a bit more low-hanging fruit if I search the disassembly for "palette"...?

**Comment by KelseyHigham** [comment]
I'm comfortable with it being closed, I can make a new issue if I look into doing that.

**Comment by kemenaran** [comment]
Ok! I guess it's better to keep issues immediately actionable, so let's close this one 👍
