### ISSUE TITLE
Repo fork status

### ISSUE THREAD

**Issue by Xkeeper0** [zladx/LADX-Disassembly#68]
This repo is marked as being a fork of iimarckus/gb-bootstrap, but it isn't really one any more. It might be worth considering asking support to [change this into a normal repo](https://stackoverflow.com/a/16052845/886398) for that reason

Not sure if they'll need more information, but the first commit that started *this* repo seems to be cd58d92c4f3dd81e342409397690804488bc777c (with 645df59207888d3e52440827644cef4924d0f571 being the last one from iimarckus/gb-bootstrap)

**Comment by kemenaran** [comment]
Yes, indeed. This has been bothering me for a while; I'll try to have a shot at the Github support.

@mojobojo to give more weight to my request, would you consider granting me admin rights to this repository?

**Comment by kemenaran** [comment]
I contacted the Github support to have the fork status removed, and they did 👍 The issue is resolved.
